[build]
  command = "echo 'No build required'"
  publish = "public"

[functions]
  directory = "netlify/functions"
  included_files = ["server/**", "requirements.txt"]

[build.environment]
  PYTHON_VERSION = "3.11"

[[redirects]]
  from = "/image/to/*"
  to = "/.netlify/functions/image"
  status = 200
  force = true

[[redirects]]
  from = "/image/thumb"
  to = "/.netlify/functions/thumb"
  status = 200
  force = true

